# Generated by Django 4.2.3 on 2023-07-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registre_etudiant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_position', models.PositiveIntegerField()),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=34)),
                ('domaine_etudiant', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
