# Generated by Django 4.2.3 on 2023-07-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registre_etudiant', '0002_etudiants_delete_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiants',
            name='id',
        ),
        migrations.AlterField(
            model_name='etudiants',
            name='id_position',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
